# Helper cell source used by the line-model loader.
# The notebook imports this module instead of embedding the source blob.

ANALYSIS_CODE_CELLS = ['# === Environment config — local CUDA / Apple Silicon (MPS) / CPU ===\n'
 '# Local one-time setup (in a terminal, inside your Python env):\n'
 '#   bash setup.sh\n'
 'import os\n'
 'import warnings\n'
 '\n'
 '# Keep notebook output focused on results rather than third-party startup noise.\n'
 "warnings.filterwarnings('ignore', category=UserWarning, module='umap')\n"
 "warnings.filterwarnings('ignore', message='.*IProgress not found.*')\n"
 "warnings.filterwarnings('ignore', message='.*DecompressionBombWarning.*')\n"
 "warnings.filterwarnings('ignore', message='.*Both `max_new_tokens`.*')\n"
 'try:\n'
 '    from PIL import Image\n'
 '    Image.MAX_IMAGE_PIXELS = None  # dataset images are trusted, very large squeeze scans\n'
 'except Exception:\n'
 '    pass\n'
 'try:\n'
 '    from transformers.utils import logging as hf_logging\n'
 '    hf_logging.set_verbosity_error()\n'
 'except Exception:\n'
 '    pass\n'
 'try:\n'
 '    from huggingface_hub.utils import logging as hub_logging\n'
 '    hub_logging.set_verbosity_error()\n'
 'except Exception:\n'
 '    pass\n'
 '\n'
 "os.environ.setdefault('PYTORCH_ENABLE_MPS_FALLBACK', '1')   # CPU fallback for unsupported MPS ops\n"
 "WORK_DIR  = os.path.abspath('data')                         # repo-local data + working dir\n"
 "CACHE_DIR = os.path.join(WORK_DIR, 'zips')                  # downloaded zips live here\n"
 '\n'
 'os.makedirs(WORK_DIR, exist_ok=True)\n'
 'os.makedirs(CACHE_DIR, exist_ok=True)\n'
 "ANN_DIR   = os.path.join(WORK_DIR, 'Annotations', 'Annotations') + os.sep\n"
 "IMG_DIR   = os.path.join(WORK_DIR, 'Images') + os.sep\n"
 "EMB_CACHE = os.path.join(WORK_DIR, 'b2_embeddings.npy')\n"
 '\n'
 'import torch\n'
 'if torch.cuda.is_available():\n'
 "    DEVICE, DTYPE = 'cuda', torch.float16\n"
 "elif getattr(torch.backends, 'mps', None) is not None and torch.backends.mps.is_available():\n"
 "    DEVICE, DTYPE = 'mps', torch.bfloat16\n"
 'else:\n'
 "    DEVICE, DTYPE = 'cpu', torch.float32\n"
 "USE_FP16 = (DEVICE == 'cuda')             # fp16 mixed-precision training only on CUDA; MPS trains fp32\n"
 '\n'
 'def empty_cache():\n'
 "    if DEVICE == 'cuda':\n"
 '        torch.cuda.empty_cache()\n'
 "    elif DEVICE == 'mps':\n"
 '        torch.mps.empty_cache()\n'
 '\n'
 '',
 '# === Shared setup: dataset index + official split ===\n'
 'import os, re, glob, random\n'
 'import numpy as np\n'
 'import pandas as pd\n'
 '\n'
 'random.seed(42); np.random.seed(42)\n'
 '\n'
 '# ANN_DIR / IMG_DIR / EMB_CACHE come from the environment-config cell.\n'
 '\n'
 '# A "base" id identifies a physical squeeze (e.g. \'IG_II2_105_Merged\'); each squeeze has\n'
 '# two lighting scans: {base}_Rotation1_300dpi and {base}_Rotation2_300dpi.\n'
 'def base_of(name):\n'
 "    name = os.path.basename(name).replace('.png', '').replace('.txt', '')\n"
 "    return re.sub(r'_Rotation\\d+_300dpi(_letters)?$', '', name)\n"
 '\n'
 '# Build an index: one row per squeeze with both rotation images + the annotation file.\n'
 '# We key on the Rotation1 letter files because the official run_evaluations() grades those.\n'
 'rows = []\n'
 "for ann in sorted(glob.glob(os.path.join(ANN_DIR, '*_Rotation1_300dpi_letters.txt'))):\n"
 '    base = base_of(ann)\n'
 "    r1 = os.path.join(IMG_DIR, f'{base}_Rotation1_300dpi.png')\n"
 "    r2 = os.path.join(IMG_DIR, f'{base}_Rotation2_300dpi.png')\n"
 '    if os.path.exists(r1) or os.path.exists(r2):\n'
 "        rows.append({'base': base, 'ann_path': ann,\n"
 "                     'rot1_img': r1 if os.path.exists(r1) else None,\n"
 "                     'rot2_img': r2 if os.path.exists(r2) else None})\n"
 'index_df = pd.DataFrame(rows)\n'
 'assert len(index_df) > 0, "No squeezes indexed — check ANN_DIR / IMG_DIR paths."\n'
 '\n'
 '\n'
 '# All (image_path, base, rotation) pairs — handy for the per-image steps below.\n'
 'img_records = []\n'
 'for _, r in index_df.iterrows():\n'
 "    for rot, col in [('rot1', 'rot1_img'), ('rot2', 'rot2_img')]:\n"
 '        if r[col]:\n'
 "            img_records.append({'base': r['base'], 'rot': rot, 'img_path': r[col],\n"
 "                                'ann_path': r['ann_path']})\n"
 'images_df = pd.DataFrame(img_records)\n'
 '\n'
 '\n'
 '# --- Per-squeeze split ----------------------------------------------------\n'
 '# The official split is required for reproducibility and comparability. If these files\n'
 '# are missing, fail loudly.\n'
 'SPLIT_DIR = os.path.dirname(ANN_DIR.rstrip(os.sep))          # parent of inner Annotations/\n'
 "official = {n: os.path.join(SPLIT_DIR, f'{n}_set.txt')\n"
 "            for n in ('training', 'validation', 'test')}\n"
 'missing = [p for p in official.values() if not os.path.exists(p)]\n'
 'if missing:\n'
 '    raise FileNotFoundError(\n'
 "        'Official split files are required for reproducible results. Missing: '\n"
 "        + ', '.join(missing)\n"
 '    )\n'
 '\n'
 'split = {}\n'
 "for split_name, fname in (('train', 'training'), ('val', 'validation'), ('test', 'test')):\n"
 '    with open(official[fname]) as f:\n'
 '        for line in f:\n'
 '            b = line.strip()\n'
 '            if b:\n'
 '                split[b] = split_name\n'
 "SPLIT_SOURCE = 'official (Annotations/{training,validation,test}_set.txt)'\n"
 '\n'
 "index_df['split'] = index_df['base'].map(split)\n"
 "images_df['split'] = images_df['base'].map(split)\n"
 '\n'
 '# Every base must end up assigned; surface mismatches loudly.\n'
 "unassigned = index_df[index_df['split'].isna()]['base'].tolist()\n"
 'if unassigned:\n'
 '    raise ValueError(\n'
 '        f"{len(unassigned)} indexed squeezes are not in the official split; "\n'
 '        f"first few: {unassigned[:5]}"\n'
 '    )\n'
 'index_df = index_df.reset_index(drop=True)\n'
 'images_df = images_df.reset_index(drop=True)\n'
 '\n'
 '',
 '# === Image preprocessing pipeline ===\n'
 '# Squeezes are 3D paper casts photographed under raking light, so the main noise\n'
 '# sources are (a) an uneven illumination gradient and (b) paper-grain speckle, on top\n'
 '# of very shallow letter impressions. The pipeline below targets exactly these.\n'
 'import cv2\n'
 'import matplotlib.pyplot as plt\n'
 '\n'
 '\n'
 'def to_gray(path):\n'
 '    return cv2.imread(path, cv2.IMREAD_GRAYSCALE)\n'
 '\n'
 '\n'
 'def preprocess_steps(gray):\n'
 '    """Return an ordered dict of intermediate images, one per cleaning step."""\n'
 '    # 1. Illumination flattening: divide out a heavily-blurred background estimate to\n'
 '    #    cancel the uneven raking-light gradient typical of squeezes.\n'
 '    bg = cv2.GaussianBlur(gray, (0, 0), sigmaX=41)\n'
 "    flat = cv2.divide(gray, bg, scale=255).astype('uint8')\n"
 '    # 2. Edge-preserving denoise to suppress paper-grain speckle.\n'
 '    den = cv2.fastNlMeansDenoising(flat, None, h=10,\n'
 '                                   templateWindowSize=7, searchWindowSize=21)\n'
 '    # 3. Local contrast enhancement (CLAHE) so shallow impressions become legible.\n'
 '    enh = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8)).apply(den)\n'
 "    return {'1. grayscale (original)': gray, '2. illumination-flattened': flat,\n"
 "            '3. denoised': den, '4. CLAHE (→ OCR)': enh}\n"
 '\n'
 '\n'
 'def preprocess(gray):\n'
 '    """Grayscale cleaning reused by the OCR pipeline (Section 3) (returns the CLAHE output)."""\n'
 "    return preprocess_steps(gray)['4. CLAHE (→ OCR)']\n"
 '\n'
 '\n'
 'def center_crop(img, s=500):\n'
 '    h, w = img.shape[:2]\n'
 '    y, x = max(0, (h - s) // 2), max(0, (w - s) // 2)\n'
 '    return img[y:y + s, x:x + s]\n'
 '\n'
 '\n'
 '# Show the SAME samples through every stage: (i) originals, (ii) steps, (iii) cleaned.\n'
 "samples = images_df.sample(4, random_state=0)['img_path'].tolist()\n"
 'fig, axes = plt.subplots(len(samples), 4, figsize=(14.4, 3.4 * len(samples)))\n'
 'for r, p in enumerate(samples):\n'
 '    steps = preprocess_steps(to_gray(p))\n'
 '    for c, (name, im) in enumerate(steps.items()):\n'
 '        ax = axes[r, c]\n'
 "        ax.imshow(center_crop(im), cmap='gray')\n"
 '        if r == 0:\n'
 '            ax.set_title(name, fontsize=10)\n'
 '        if c == 0:\n'
 '            ax.set_xticks([]); ax.set_yticks([])\n'
 "            ax.set_ylabel(os.path.basename(p).replace('_300dpi.png', '')[:22], fontsize=8)\n"
 '        else:\n'
 '            ax.set_axis_off()\n'
 "plt.suptitle('Preprocessing stages (center 500×500 crop per squeeze)', y=1.002)\n"
 'plt.tight_layout(); plt.show()',
 '# Baseline model: pretrained TrOCR (printed). Plan: (1) measure its CER as-is on the\n'
 '# held-out test squeezes, then (2) fine-tune it on squeeze line-crops and show the gain.\n'
 '# NOTE: line extraction + evaluation live AFTER the official eval script below, because\n'
 '# they reuse its helpers (readBoxFile, getRowBoxes, ...). This cell loads the model and\n'
 '# defines the decoding helpers: greedy/beam search, an optional alphabet constraint, and\n'
 '# a scored variant used to ensemble the two raking-light rotations at test time.\n'
 'import numpy as np, cv2, os\n'
 'import torch\n'
 'from PIL import Image\n'
 'from transformers import (TrOCRProcessor, VisionEncoderDecoderModel,\n'
 '                          LogitsProcessor, LogitsProcessorList)\n'
 'from transformers.utils import logging as hf_logging\n'
 'hf_logging.set_verbosity_error()\n'
 '\n'
 'device = DEVICE\n'
 '# Base checkpoint is configurable (Phase 2, item 7): try a handwritten/large variant.\n'
 '#   TROCR_BASE=microsoft/trocr-base-handwritten   (engraved letters resemble handwriting)\n'
 '#   TROCR_BASE=microsoft/trocr-large-printed\n'
 "BASE_CKPT = os.environ.get('TROCR_BASE', 'microsoft/trocr-base-printed')\n"
 'processor = TrOCRProcessor.from_pretrained(BASE_CKPT)\n'
 'baseline_model = VisionEncoderDecoderModel.from_pretrained(BASE_CKPT, low_cpu_mem_usage=False).to(device).eval()\n'
 'baseline_model.config.max_length = None\n'
 'baseline_model.config.num_beams = None\n'
 'baseline_model.generation_config.max_length = None\n'
 'baseline_model.generation_config.num_beams = None\n'
 'baseline_model.generation_config.max_new_tokens = None\n'
 '\n'
 '\n'
 '# --- Aspect-ratio-preserving input (Phase 2, item 6) --------------------------\n'
 "# TrOCR's image processor stretches every crop to 384x384, which vertically\n"
 '# distorts wide line-crops and warps letter shapes. Instead we letterbox each crop\n'
 "# (resize preserving aspect ratio, then pad to a square with the crop's median\n"
 "# tone), so the processor's resize is an identity op and letters keep their shape.\n"
 '# Used by BOTH training (LineDataset) and inference, so the distributions match.\n'
 'PROC_SIZE = 384\n'
 '# NOTE: default OFF. Naive letterboxing pads a short line into a 384^2 canvas, so\n'
 '# the ViT mostly sees background and the (un-tuned) baseline degrades badly. Kept as\n'
 '# an opt-in knob to A/B against the default stretch once the model is retrained.\n'
 "KEEP_ASPECT = os.environ.get('KEEP_ASPECT', '0') == '1'\n"
 '\n'
 '\n'
 'def prep_image(pil, size=PROC_SIZE):\n'
 '    """RGB size x size image. Letterbox when KEEP_ASPECT, else plain RGB (the\n'
 '    processor then stretches it, i.e. the original behaviour)."""\n'
 '    if not KEEP_ASPECT:\n'
 "        return pil.convert('RGB')\n"
 "    im = pil.convert('L')\n"
 '    w, h = im.size\n'
 '    s = size / max(w, h)\n'
 '    nw, nh = max(1, round(w * s)), max(1, round(h * s))\n'
 '    im = im.resize((nw, nh), Image.BILINEAR)\n'
 '    pad = int(np.median(np.asarray(im)))\n'
 "    canvas = Image.new('L', (size, size), color=pad)\n"
 '    canvas.paste(im, ((size - nw) // 2, (size - nh) // 2))\n'
 "    return canvas.convert('RGB')\n"
 '\n'
 '\n'
 '# --- Optional alphabet-constrained decoding -----------------------------------\n'
 "# The proxy targets use a small alphabet (the 24 Greek->Latin proxy letters + ':').\n"
 "# TrOCR's subword vocab can otherwise emit digits, punctuation or foreign letters, so we\n"
 '# can mask the decoder logits to a legal token set. Two modes:\n'
 "#   'charset'    : allow any token whose characters are all in the alphabet (+ space).\n"
 "#   'singlechar' : allow only single-character tokens -> forces char-by-char decoding,\n"
 '#                  which matches the scriptio-continua target most closely.\n'
 'class AllowedTokensLogitsProcessor(LogitsProcessor):\n'
 '    def __init__(self, allowed_ids, vocab_size, device):\n'
 "        mask = torch.full((vocab_size,), float('-inf'))\n"
 '        mask[torch.tensor(sorted(allowed_ids), dtype=torch.long)] = 0.0\n'
 '        self.mask = mask.to(device)\n'
 '\n'
 '    def __call__(self, input_ids, scores):\n'
 '        return scores + self.mask\n'
 '\n'
 '\n'
 "def build_allowed_token_ids(allowed_chars, mode='charset'):\n"
 '    """Token ids whose decoded text is legal under `mode` (special tokens always kept)."""\n'
 '    tok = processor.tokenizer\n'
 '    allowed = set(c.upper() for c in allowed_chars)\n'
 '    ids = set(int(i) for i in tok.all_special_ids if i is not None)\n'
 '    for tid in range(len(tok)):\n'
 '        core = tok.decode([tid], skip_special_tokens=True).strip()\n'
 "        if core == '':\n"
 '            ids.add(tid)                      # empty/space tokens; spaces stripped at scoring\n'
 '            continue\n'
 '        if not all(c.upper() in allowed for c in core):\n'
 '            continue\n'
 "        if mode == 'singlechar' and len(core) != 1:\n"
 '            continue\n'
 '        ids.add(tid)\n'
 '    return sorted(ids)\n'
 '\n'
 '\n'
 "def make_logits_processor(allowed_chars, mode='charset'):\n"
 '    ids = build_allowed_token_ids(allowed_chars, mode=mode)\n'
 '    return LogitsProcessorList(\n'
 '        [AllowedTokensLogitsProcessor(ids, len(processor.tokenizer), device)])\n'
 '\n'
 '\n'
 '@torch.no_grad()\n'
 'def trocr_transcribe(model, pil_lines, bs=16, max_new_tokens=64,\n'
 '                     num_beams=1, logits_processor=None):\n'
 '    """Transcribe a list of PIL line-images; returns a list of strings.\n'
 '\n'
 '    num_beams>1 enables beam search; logits_processor optionally constrains the\n'
 '    output alphabet (see make_logits_processor)."""\n'
 '    texts = []\n'
 '    for i in range(0, len(pil_lines), bs):\n'
 '        batch = [prep_image(im) for im in pil_lines[i:i + bs]]\n'
 "        pix = processor(images=batch, return_tensors='pt').pixel_values.to(device)\n"
 '        ids = model.generate(pix, max_new_tokens=max_new_tokens, use_cache=True,\n'
 '                             num_beams=num_beams, logits_processor=logits_processor)\n'
 '        texts.extend(processor.batch_decode(ids, skip_special_tokens=True))\n'
 '    return texts\n'
 '\n'
 '\n'
 '@torch.no_grad()\n'
 'def trocr_transcribe_scored(model, pil_lines, bs=16, max_new_tokens=64,\n'
 '                            num_beams=1, logits_processor=None):\n'
 '    """Like trocr_transcribe but also returns a length-normalized log-prob per line,\n'
 '    used to pick the more confident reading when ensembling the two rotations."""\n'
 '    texts, confs = [], []\n'
 '    for i in range(0, len(pil_lines), bs):\n'
 '        batch = [prep_image(im) for im in pil_lines[i:i + bs]]\n'
 "        pix = processor(images=batch, return_tensors='pt').pixel_values.to(device)\n"
 '        gen = model.generate(pix, max_new_tokens=max_new_tokens, use_cache=True,\n'
 '                             num_beams=num_beams, logits_processor=logits_processor,\n'
 '                             output_scores=True, return_dict_in_generate=True)\n'
 '        tr = model.compute_transition_scores(\n'
 "            gen.sequences, gen.scores, getattr(gen, 'beam_indices', None),\n"
 '            normalize_logits=True)\n'
 '        finite = torch.isfinite(tr)\n'
 '        seq_conf = tr.masked_fill(~finite, 0.0).sum(1) / finite.sum(1).clamp(min=1)\n'
 '        texts.extend(processor.batch_decode(gen.sequences, skip_special_tokens=True))\n'
 '        confs.extend(seq_conf.float().cpu().tolist())\n'
 '    return texts, confs\n'
 '\n'
 '',
 '# Official ICDAR 2026 Contest Evaluation (Nicholas Howe, CC-BY 4.0)\n'
 '# Source: contest_evaluation/contest_evaluation.py\n'
 '# Requires: pip install textdistance\n'
 '\n'
 '# -*- coding: utf-8 -*-\n'
 '"""\n'
 'Code released in conjunction with the 2026 ICDAR Competition in \n'
 'Text Recognition on Greek Squeezes (TROGS-26)\n'
 '\n'
 'Call run_evaluations(pred_dir,gt_dir) to evaluate.\n'
 "pred_dir should contain your method's transcription files\n"
 '    Filenames should be {squeeze}_transcript.txt\n'
 '    Contents are line by line character transcriptions\n'
 'gt_dir should contain letter box files with ground truth\n'
 '\n'
 '@author: Nicholas Howe  CC-BY 4.0\n'
 '"""\n'
 '\n'
 'import math\n'
 'import os\n'
 'from os import listdir\n'
 'from os.path import isfile, join\n'
 'import numpy as np\n'
 'from textdistance import levenshtein\n'
 'import matplotlib.pyplot as plt\n'
 '\n'
 'VERBOSE_EVAL = False\n'
 '\n'
 'class Box:\n'
 "    '''\n"
 '    # simple class to keep track of coordinates for the four corners of a box\n'
 '    # note corner order is CCW from NW corner, as stored in letter box file\n'
 "    '''\n"
 '    def __init__(self,xnw,ynw,xsw,ysw,xse,yse,xne,yne):\n'
 '        self.xnw = xnw\n'
 '        self.ynw = ynw\n'
 '        self.xsw = xsw\n'
 '        self.ysw = ysw\n'
 '        self.xse = xse\n'
 '        self.yse = yse\n'
 '        self.xne = xne\n'
 '        self.yne = yne\n'
 '        \n'
 '    def bd(self):\n'
 '        return [self.xnw,self.ynw,self.xsw,self.ysw,self.xse,self.yse,self.xne,self.yne]\n'
 '\n'
 '    def center(self):\n'
 '        return((self.xnw+self.xne+self.xse+self.xsw)/4,(self.ynw+self.yne+self.yse+self.ysw)/4)\n'
 '    \n'
 '    def radius(self):\n'
 '        return '
 '(math.sqrt((self.xnw-self.xse)*(self.xnw-self.xse)+(self.ynw-self.yse)*(self.ynw-self.yse))+math.sqrt((self.xne-self.xsw)*(self.xne-self.xsw)+(self.yne-self.ysw)*(self.yne-self.ysw)))/4\n'
 '    \n'
 '    def area(self):\n'
 '        # uses top and left side, assuming orthogonal rectangle\n'
 '        return '
 'math.sqrt(((self.xne-self.xnw)**2+(self.yne-self.ynw)**2)*((self.xsw-self.xnw)**2+(self.ysw-self.ynw)**2))\n'
 '\n'
 '    def angle(self):\n'
 '        return math.atan2(self.yne-self.ynw,self.xne-self.xnw)\n'
 '\n'
 '    def dist(self,box):\n'
 '        c = self.center()\n'
 '        c2 = box.center()\n'
 '        return math.sqrt((c[0]-c2[0])*(c[0]-c2[0])+(c[1]-c2[1])*(c[1]-c2[1]))\n'
 '\n'
 "    def plot(self,clr='r-'):\n"
 '        plt.plot([self.xnw,self.xne,self.xse,self.xsw,self.xnw],[self.ynw,self.yne,self.yse,self.ysw,self.ynw],clr)\n'
 '        \n'
 '      \n'
 'def convert(stringin):\n'
 '    """\n'
 '    Convert Greek characters to letter proxies.\n'
 '\n'
 '    Parameters\n'
 '    ----------\n'
 '    stringin : String\n'
 '        Character string possibly containing Greek.\n'
 '\n'
 '    Returns\n'
 '    -------\n'
 '    txt : String\n'
 '        Converted string with Greek characters replaced by Latin proxy.\n'
 '\n'
 '    """\n'
 '    eqv = {\n'
 '        913:"A",  # ALPHA\n'
 '        7944:"A", # ALPHA + AIGU\n'
 '        914:"B",  # BETA\n'
 '        915:"G",  # GAMMA\n'
 '        916:"D",  # DELTA\n'
 '        917:"E",  # EPSILON\n'
 '        918:"Z",  # ZETA\n'
 '        919:"H",  # ETA\n'
 '        920:"Q",  # THETA\n'
 '        921:"I",  # IOTA\n'
 '        922:"K",  # KAPPA\n'
 '        923:"L",  # LAMDA\n'
 '        924:"M",  # MU\n'
 '        925:"N",  # NU\n'
 '        926:"X",  # XI\n'
 '        927:"O",  # OMICRON\n'
 '        928:"P",  # PI\n'
 '        929:"R",  # PI\n'
 '        931:"S",  # SIGMA\n'
 '        932:"T",  # TAU\n'
 '        933:"U",  # UPSILON\n'
 '        934:"F",  # PHI\n'
 '        935:"Y",  # PSI\n'
 '        936:"C",  # CHI\n'
 '        937:"W",  # OMEGA\n'
 '        945:"a",  # ALPHA\n'
 '        8118:"a",  # ALPHA + TILDE\n'
 '        8119:"a",  # ALPHA + TILDE + CEDILLE\n'
 '        7942:"a",  # ALPHA + TILDE + TICK\n'
 '        7943:"a",  # ALPHA + TILDE + BACKTICK\n'
 '        8070:"a",  # ALPHA + TILDE + TICK + CEDILLE\n'
 '        8071:"a",  # ALPHA + TILDE + BACKTICK + CEDILLE\n'
 '        8048:"a",  # ALPHA + GRAVE\n'
 '        8049:"a",  # ALPHA + AIGU\n'
 '        7936:"a",  # ALPHA + TICK\n'
 '        7937:"a",  # ALPHA +BACKTICK\n'
 '        7940:"a",  # ALPHA + TICK + AIGU\n'
 '        7941:"a",  # ALPHA + BACKTICK + AIGU\n'
 '        7938:"a",  # ALPHA + TICK + GRAVE\n'
 '        7939:"a",  # ALPHA + BACKTICK + GRAVE\n'
 '        946:"b",  # BETA\n'
 '        947:"g",  # GAMMA\n'
 '        948:"d",  # DELTA\n'
 '        949:"e",  # EPSILON\n'
 '        7952:"e",  # EPSILON + TICK\n'
 '        7953:"e",  # EPSILON + BACKTICK\n'
 '        8050:"e",  # EPSILON + GRAVE\n'
 '        8051:"e",  # EPSILON + AIGU\n'
 '        7956:"e",  # EPSILON + TICK + AIGU\n'
 '        7957:"e",  # EPSILON + BACKTICK + AIGU\n'
 '        7954:"e",  # EPSILON + TICK + GRAVE\n'
 '        7955:"e",  # EPSILON + BACKTICK + GRAVE\n'
 '        950:"z",  # ZETA\n'
 '        951:"h",  # ETA\n'
 '        7974:"h",  # ETA + TILDE + TICK + CEDILLE\n'
 '        7975:"h",  # ETA + TILDE + BACKTICK + CEDILLE\n'
 '        8086:"h",  # ETA + TILDE + TICK\n'
 '        8087:"h",  # ETA + TILDE + BACKTICK\n'
 '        8134:"h",  # ETA + TILDE\n'
 '        8135:"h",  # ETA + TILDE + CEDILLE\n'
 '        7970:"h",  # ETA + TICK + GRAVE\n'
 '        7971:"h",  # ETA + BACKTICK + GRAVE\n'
 '        8016:"h",  # ETA + TICK?\n'
 '        8020:"h",  # ETA + TICK + AIGU\n'
 '        7968:"h",  # ETA + TICK\n'
 '        7969:"h",  # ETA + BACKTICK\n'
 '        7972:"h",  # ETA + TICK + AIGU\n'
 '        7973:"h",  # ETA + BACKTICK + AIGU\n'
 '        8052:"h",  # ETA + GRAVE\n'
 '        8053:"h",  # ETA + AIGU ?\n'
 '        952:"q",  # THETA\n'
 '        953:"i",  # IOTA\n'
 '        7990:"i",  # IOTA + TILDE + TICK\n'
 '        7991:"i",  # IOTA + TILDE + BACKTICK\n'
 '        8150:"i",  # IOTA + TILDE\n'
 '        8054:"i",  # IOTA + GRAVE\n'
 '        8055:"i",  # IOTA + AIGU\n'
 '        7984:"i",  # IOTA + TICK\n'
 '        7985:"i",  # IOTA + BACKTICK\n'
 '        7988:"i",  # IOTA + TICK + AIGU\n'
 '        7989:"i",  # IOTA + BACKTICK + AIGU\n'
 '        7986:"i",  # IOTA + TICK + GRAVE\n'
 '        7987:"i",  # IOTA + BACKTICK + GRAVE\n'
 '        954:"k",  # KAPPA\n'
 '        955:"l",  # LAMDA\n'
 '        956:"m",  # MU\n'
 '        957:"n",  # NU\n'
 '        834:"n",  # NU + TILDE\n'
 '        958:"x",  # XI\n'
 '        959:"o",  # OMICRON\n'
 '        8056:"o",  # OMICRON + GRAVE\n'
 '        8057:"o",  # OMICRON + AIGU\n'
 '        8000:"o",  # OMICRON + TICK\n'
 '        8001:"o",  # OMICRON + BACKTICK\n'
 '        8004:"o",  # OMICRON + TICK + AIGU\n'
 '        8005:"o",  # OMICRON + BACKTICK + AIGU\n'
 '        8002:"o",  # OMICRON + TICK + GRAVE\n'
 '        8003:"o",  # OMICRON + BACKTICK + GRAVE\n'
 '        960:"p",  # PI\n'
 '        961:"r",  # RHO\n'
 '        962:"v",  # SIGMA\n'
 '        963:"s",  # SIGMA\n'
 '        964:"t",  # TAU\n'
 '        965:"u",  # UPSILON\n'
 '        8022:"u",  # UPSILON + TILDE + TICK\n'
 '        8023:"u",  # UPSILON + TILDE + BACKTICK\n'
 '        8166:"u",  # UPSILON + TILDE\n'
 '        8016:"u",  # UPSILON + TICK\n'
 '        8017:"u",  # UPSILON + BACKTICK\n'
 '        8020:"u",  # UPSILON + TICK + AIGU\n'
 '        8021:"u",  # UPSILON + BACKTICK + AIGU\n'
 '        8018:"u",  # UPSILON + TICK + GRAVE\n'
 '        8019:"u",  # UPSILON + BACKTICK + GRAVE\n'
 '        8058:"u",  # UPSILON + GRAVE\n'
 '        8059:"u",  # UPSILON + AIGU ?\n'
 '        966:"f",  # PHI\n'
 '        967:"y",  # PSI\n'
 '        968:"c",  # CHI\n'
 '        969:"w",  # OMEGA\n'
 '        8102:"w",  # OMEGA + TILDE + TICK + CEDILLE\n'
 '        8103:"w",  # OMEGA + TILDE + BACKTICK + CEDILLE\n'
 '        8038:"w",  # OMEGA + TILDE + TICK\n'
 '        8039:"w",  # OMEGA + TILDE + BACKTICK\n'
 '        8182:"w",  # OMEGA + TILDE\n'
 '        8183:"w",  # OMEGA + TILDE + CEDILLE\n'
 '        8060:"w",  # OMEGA + GRAVE\n'
 '        8061:"w",  # OMEGA + AIGU\n'
 '        8032:"w",  # OMEGA + TICK\n'
 '        8033:"w",  # OMEGA + BACKTICK\n'
 '        8036:"w",  # OMEGA + TICK + AIGU\n'
 '        8037:"w",  # OMEGA + BACKTICK + AIGU\n'
 '        8034:"w",  # OMEGA + TICK + GRAVE\n'
 '        8035:"w",  # OMEGA + BACKTICK + GRAVE\n'
 '    \n'
 '        8217:"\'",  # TICK???\n'
 '        8025:"`",  # BACKTICK???\n'
 '        803:"_",  # CEDILLE???\n'
 '        8195:" ",  # WEIRD SPACE???\n'
 '        903:".",  # WEIRD DOT???\n'
 '        8228:".",  # WEIRD DOT???\n'
 '        8311:"7",  # SUPERSCRIPT 7\n'
 '    \n'
 '        # Formatting characters\n'
 '        10:"\\n",  # CARRIAGE RETURN\n'
 '        3:" ",  # SPACE\n'
 '        32:" "  # SPACE\n'
 '    }\n'
 '    for i in range(0, 254):\n'
 '        eqv[i] = chr(i)\n'
 '            \n'
 '    txt = []\n'
 '    for char in stringin:\n'
 '        if ord(char) in eqv:\n'
 '            txt.append(eqv[ord(char)])\n'
 '        else:\n'
 '            txt.append(char)               \n'
 '    txt = "".join(txt)\n'
 '    return txt.upper()\n'
 '\n'
 '\n'
 'def readBoxFile(fname):\n'
 '    """\n'
 '    Parameters\n'
 '    ----------\n'
 '    fname : Name of the file to read\n'
 '\n'
 '    Returns\n'
 '    -------\n'
 '    angle : Primary angle of the text\n'
 '    boxes : List of boxes\n'
 '    transcript : Box annotations\n'
 '    lines : Information about how boxes are arranged in lines\n'
 '    """\n'
 '    angle = None\n'
 '    boxes = []\n'
 '    transcript = []\n'
 '    lines = []\n'
 '    try:\n'
 '        with open(fname, "r") as f:\n'
 '            phase = 0\n'
 '            count = 0\n'
 '            for line in f:\n'
 '                count = count+1\n'
 "                line2 = line.replace('*','').replace(' ','')\n"
 "                if line2=='' or line2=='\\n':\n"
 '                    continue  # skip empty line\n'
 "                elif line[0]=='#':\n"
 '                    phase = phase+1\n'
 '                elif phase==0:  # File should begin with a comment\n'
 "                    #if line[0]=='# Baseline angle\\n':\n"
 '                    if VERBOSE_EVAL:\n'
 '                        print("Header problem in file {}.".format(fname))\n'
 '                elif phase==1:\n'
 "                    #if line=='# Boxes: x1 y1 x2 y2 x3 y3 x4 y4\\n':\n"
 '                    if angle==None:\n'
 '                        angle = float(line)\n'
 '                    else:\n'
 '                        if VERBOSE_EVAL:\n'
 '                            print("Multiple angle data found in {}.".format(fname))\n'
 '                elif phase==2:\n'
 "                    #if line=='# Transcript\\n':\n"
 '                    n = line.split()\n'
 '                    if len(n)==8:\n'
 '                        box = Box(*[float(c) for c in n])\n'
 '                        if box.area() < 9:\n'
 '                            if VERBOSE_EVAL:\n'
 '                                print("Skipping box with very small area (line {}).".format(count))\n'
 '                        else:\n'
 '                            boxes.append(box)\n'
 '                    else:\n'
 '                        if VERBOSE_EVAL:\n'
 "                            print('Incorrect parameter count for box line ({}) in {}.'.format(len(n),fname))   \n"
 '                elif phase==3:\n'
 "                    transcript.append(line.replace('*','').replace('\\n','').replace('\\r','').replace(' ',''))\n"
 '                elif phase==4:\n'
 '                    n = line.split()\n'
 '                    if len(n)==4:\n'
 '                        lines.append([float(c) for c in n])\n'
 '                        if np.any(np.isnan(lines[-1])):\n'
 '                            if VERBOSE_EVAL:\n'
 "                                print('Bad values found in line specification (file line {}) -- "
 "skipping.'.format(count))\n"
 '                            lines.pop()\n'
 '                        elif lines[-1][0]==lines[-1][2] and lines[-1][1]==lines[-1][3]:\n'
 '                            if VERBOSE_EVAL:\n'
 "                                print('Zero-length line found in line specification (file line {}) -- "
 "skipping.'.format(count))\n"
 '                            lines.pop()\n'
 '                    else:\n'
 '                        if VERBOSE_EVAL:\n'
 "                            print('Incorrect parameter count for line specifiers ({}) in "
 "{}.'.format(len(n),fname))   \n"
 '            f.close()\n'
 '    except FileNotFoundError:\n'
 '        if VERBOSE_EVAL:\n'
 '            print(f"File \'{fname}\' not found.")\n'
 '    except Exception as e:\n'
 '        if VERBOSE_EVAL:\n'
 '            print(f"An error occurred: {str(e)}")\n'
 '    return angle,boxes,transcript,lines\n'
 '\n'
 '\n'
 'def dist2seg(x,y,seg):\n'
 "    '''\n"
 '    # compute the distance from a point to the nearest point on a line segment\n'
 "    '''\n"
 '    x0 = seg[0]\n'
 '    y0 = seg[1]\n'
 '    x1 = seg[2]\n'
 '    y1 = seg[3]\n'
 '    rx = x-x0\n'
 '    ry = y-y0\n'
 '    rx1 = x1-x0\n'
 '    ry1 = y1-y0\n'
 '    seglen = math.sqrt(rx1**2+ry1**2)\n'
 '    parcomp = (rx*rx1+ry*ry1)/seglen\n'
 '    if parcomp<0:\n'
 '        # closest point is p0 endpoint\n'
 '        d = math.sqrt(rx**2+ry**2)\n'
 '    elif parcomp > seglen:\n'
 '        # closest point is p1 endpoint\n'
 '        d = math.sqrt((x-x1)**2+(y-y1)**2)\n'
 '    else:\n'
 '        # find closest point p along segment\n'
 '        t = parcomp/seglen\n'
 '        px = x0+t*rx1\n'
 '        py = y0+t*ry1\n'
 '        d = math.sqrt((x-px)**2+(y-py)**2)\n'
 '    return d\n'
 '\n'
 '\n'
 'def getRowBoxes(boxes,gangle=None,lines=[]):\n'
 '    """\n'
 '    Orders a set of boxes into rows.\n'
 '    Designed to work with data from a letter box file.\n'
 '    """\n'
 '    if len(lines)==0:\n'
 '        # infer lines by spatial arrangement\n'
 '        nboxes = len(boxes)\n'
 '        bclust = np.full((nboxes),-1)\n'
 '        bseq = np.zeros((nboxes))\n'
 '        lnbr = np.full((nboxes),-1)\n'
 '        rnbr = np.full((nboxes),-1)\n'
 '        \n'
 '        # speed up inner loop by sorting x coordinates\n'
 '        xcent = [b.center()[0] for b in boxes]\n'
 '        xsort = np.sort(xcent)\n'
 '        xord = np.argsort(xcent)\n'
 '        xlut = np.argsort(xord)\n'
 '    \n'
 '        # find left and right nearest neighbors for each box\n'
 '        for i in range(nboxes):\n'
 '            ci = boxes[i].center()\n'
 '            if (gangle==None):\n'
 '                # no global angle so compute a local one from the top line of this box\n'
 '                angle = boxes[i].angle()\n'
 '            else:\n'
 '                angle = gangle\n'
 '            ax = math.cos(angle)\n'
 '            ay = math.sin(angle)\n'
 '            rd = np.inf  # current distance to closest right leighbor\n'
 '            ld = np.inf  # current distance to closest left neighbor\n'
 '            # we are going to start at the x value of the current box, and check nearby\n'
 '            # values of x both higher and lower\n'
 '            klo = xlut[i]\n'
 '            khi = klo\n'
 '            assert(ci[0] == xsort[klo])\n'
 '            while min(ci[0]-xsort[klo],xsort[khi]-ci[0]) < max(rd,ld) and (klo>0 or khi < nboxes-1):\n'
 '                if (ci[0]-xsort[klo] < xsort[khi]-ci[0] or khi >= nboxes-1) and klo > 0:\n'
 '                    # reduce klo\n'
 '                    klo = klo-1\n'
 '                    j = xord[klo]  # next closest x value below\n'
 '                elif khi < nboxes-1:\n'
 '                    # increase khi\n'
 '                    khi = khi+1\n'
 '                    j = xord[khi]  # next closest x value above\n'
 '                else:\n'
 '                    if VERBOSE_EVAL:\n'
 "                        print('Should not reach this!')\n"
 '                # check whether box j is closer to i on either the left or the right\n'
 '                d = boxes[i].dist(boxes[j])\n'
 '                cj = boxes[j].center()\n'
 '                rj = boxes[j].radius();\n'
 '                rjsq = rj*rj\n'
 '                dcx = cj[0]-ci[0]\n'
 '                dcy = cj[1]-ci[1]\n'
 '                dotprod = dcx*ax+dcy*ay\n'
 '                isRight = dotprod > 0\n'
 '                if (i!=j) and (d<ld) and not isRight:\n'
 '                    # found a closer left neighbor, so check position and update if near line\n'
 '                    c = (ci[0]-d*ax, ci[1]-d*ay)\n'
 '                    if (cj[0]-c[0])**2+(cj[1]-c[1])**2 < rjsq:\n'
 '                        ld = d\n'
 '                        lnbr[i] = j\n'
 '                if (i!=j) and (d<rd) and isRight:\n'
 '                    # found a closer right neighbor, so check position and update if near line\n'
 '                    c = (ci[0]+d*ax, ci[1]+d*ay)\n'
 '                    if (cj[0]-c[0])**2+(cj[1]-c[1])**2 < rjsq:\n'
 '                        rd = d\n'
 '                        rnbr[i] = j\n'
 '                #print(i,j)\n'
 '        \n'
 '        # sanity/correctness check for neighbor detection -- hopefully should never report a mismatch.\n'
 '        for i in range(len(rnbr)):\n'
 '            if rnbr[i]>=0 and lnbr[rnbr[i]]!=i:\n'
 '                if lnbr[rnbr[i]] >= 0 and rnbr[lnbr[rnbr[i]]] == rnbr[i]:\n'
 '                    # pointing to a neighbor that is mutually satisfied; this link is probably wrong\n'
 '                    rnbr[i] = -2\n'
 '            if lnbr[i]>=0 and rnbr[lnbr[i]]!=i:\n'
 '                if rnbr[lnbr[i]] >= 0 and lnbr[rnbr[lnbr[i]]] == lnbr[i]:\n'
 '                    # pointing to a neighbor that is mutually satisfied; this link is probably wrong\n'
 '                    lnbr[i] = -2\n'
 '        for i in range(len(rnbr)):\n'
 '            if rnbr[i]>=0 and lnbr[rnbr[i]]!=i:\n'
 '                if lnbr[rnbr[i]]<0:\n'
 '                    # link up unassigned box\n'
 '                    lnbr[rnbr[i]] = i\n'
 '                else:\n'
 '                    if VERBOSE_EVAL:\n'
 "                        print('Left of right mismatch at {}: {} to {}.'.format(i,rnbr[i],lnbr[rnbr[i]]))\n"
 '                    #lnbr[rnbr[i]] = -3\n'
 '                    #rnbr[i]=-3\n'
 '            if lnbr[i]>=0 and rnbr[lnbr[i]]!=i:\n'
 '                if rnbr[lnbr[i]]<0:\n'
 '                    # link up unassigned box\n'
 '                    rnbr[lnbr[i]] = i\n'
 '                else:\n'
 '                    if VERBOSE_EVAL:\n'
 "                        print('Right of left mismatch at {}: {} to {}.'.format(i,lnbr[i],rnbr[lnbr[i]]))\n"
 '                    #rnbr[lnbr[i]] = -3\n'
 '                    #lnbr[i] = -3\n'
 '    \n'
 '        # cluster boxes by row: combine nearest neighbors one by one\n'
 '        clust = 0\n'
 '        cid = []\n'
 '        cseq = []\n'
 '        for i in range(nboxes):\n'
 '            if (gangle==None):\n'
 '                angle = boxes[i].angle()\n'
 '            else:\n'
 '                angle = gangle\n'
 '            if (bclust[i] == -1):\n'
 '                # we have found a box belonging to a new cluster, so assemble all of its neighbors and give them the '
 'same cluster label\n'
 '                c = [i]\n'
 '                bclust[i] = clust\n'
 '                bseq[i] = boxes[i].center()[0]*math.cos(angle)+boxes[i].center()[1]*math.sin(angle)\n'
 '                j = lnbr[i]\n'
 '                while (j>=0) and not j in c:\n'
 '                    bclust[j] = clust\n'
 '                    c.append(j)\n'
 '                    bseq[j] = boxes[j].center()[0]*math.cos(angle)+boxes[j].center()[1]*math.sin(angle)\n'
 '                    j = lnbr[j]\n'
 '                j = rnbr[i]\n'
 '                while (j>=0) and not j in c:\n'
 '                    bclust[j] = clust\n'
 '                    c.append(j)\n'
 '                    bseq[j] = boxes[j].center()[0]*math.cos(angle)+boxes[j].center()[1]*math.sin(angle)\n'
 '                    j = rnbr[j]\n'
 '                cseq.append(-boxes[i].center()[0]*math.sin(angle)+boxes[i].center()[1]*math.cos(angle))\n'
 '                cid.append(c)\n'
 '                clust = clust+1\n'
 '            # the new cluster is now labeled\n'
 '            #print(clust,c,cseq,bseq)\n'
 '        \n'
 '        rowlist = []\n'
 '        # at the end of this loop, all the boxes are labeled with a unique cluster id.\n'
 '        # they may not be sorted left to right or top to bottom yet\n'
 '        # cseq holds a value that increases from top to bottom, \n'
 '        # and bseq holds a value that increases from left to right within a row\n'
 '        # so the boxes should be reordered and assembled according to these numbers.\n'
 '        # use ord2lut to convert the numeric values to a list of indices that are in the correct order\n'
 '        for c in cid:\n'
 '            # c is a list of the box ids belonging to this cluster\n'
 '            rowlist.append([boxes[c[i]] for i in np.argsort(bseq[c])])\n'
 '        return [rowlist[i] for i in np.argsort(cseq)], [cid[i] for i in np.argsort(cseq)]  # reorder rows based on '
 'cseq value\n'
 '    else:\n'
 '        # attribute boxes to lines based on supplied line information\n'
 '        # first, identify any polylines:\n'
 '        label = np.zeros(len(lines),dtype=np.int32)\n'
 '        for i in range(1,len(lines)):\n'
 '            if lines[i][0]==lines[i-1][2] and lines[i][1]==lines[i-1][3]:\n'
 '                # we have a continuation\n'
 '                label[i] = label[i-1]\n'
 '            else:\n'
 '                # new polyline\n'
 '                label[i] = label[i-1]+1\n'
 '\n'
 '        # next, find min distance from each box to a line segment\n'
 '        blabel = np.zeros(len(boxes))\n'
 '        for i in range(len(boxes)):\n'
 '            d = dist2seg(*boxes[i].center(),lines[0])\n'
 '            blabel[i] = 0\n'
 '            for j in range(1,len(lines)):\n'
 '                jd = dist2seg(*boxes[i].center(),lines[j])\n'
 '                if jd<d:\n'
 '                    d = jd\n'
 '                    blabel[i] = label[j]\n'
 '                    \n'
 '        # now arrange the boxes within the rows\n'
 '        rowlist = []\n'
 '        idlist = []\n'
 '        for i in range(label[-1]+1):\n'
 '            j = 0\n'
 '            while j < len(boxes) and blabel[j]!=i:  # keep going until we find the first box with label i\n'
 '                j = j+1\n'
 '            if j<len(boxes):  # just make sure we found at least one box assigned to this label\n'
 '                row = [boxes[j]]\n'
 '                rowid = [j]\n'
 '                rank = [0]\n'
 '                for k in range(j+1,len(boxes)):\n'
 '                    if blabel[k]==i:\n'
 '                        row.append(boxes[k])\n'
 '                        rowid.append(k)\n'
 '                        '
 'rank.append((boxes[k].xnw-boxes[j].xnw)*(boxes[j].xne-boxes[j].xnw)+(boxes[k].ynw-boxes[j].ynw)*(boxes[j].yne-boxes[j].ynw))\n'
 '                # now we have all the boxes in this row, and rank holds a value that will sort them\n'
 '                rowlist.append([row[i] for i in np.argsort(rank)])\n'
 '                idlist.append([rowid[i] for i in np.argsort(rank)])\n'
 '        return rowlist, idlist\n'
 '    \n'
 '    \n'
 'def orderBoxes(boxes,gangle=None,lines=[]):\n'
 '    rowlist, idlist = getRowBoxes(boxes,gangle=gangle,lines=lines)\n'
 '    return [b for row in rowlist for b in row]\n'
 '\n'
 '\n'
 'def getRowTranscript(fname):\n'
 '      """\n'
 '      Reads a file of annotated letter boxes and arranges them into rows \n'
 '      ordered from left to right.\n'
 '     \n'
 '      For contest grading purposes, we want to use simple left-to-right,\n'
 '      top down reading order, explicitly ignoring multicolumn layouts.\n'
 '      \n'
 '      To make sure the transcript matches, we need to first generate the \n'
 '      multicolumn result and then reorder into full-width lines.\n'
 '      """   \n'
 '      gangle, boxes, transcript, lines = readBoxFile(fname)\n'
 '      boxes2 = orderBoxes(boxes,gangle,lines)  # reordered to transcript order\n'
 '      rowlist, idlist = getRowBoxes(boxes2,gangle=gangle)  # ignore multicolumn\n'
 "      lintran = ''.join(transcript)\n"
 "      return ''.join([''.join([lintran[i] for i in rowid])+'\\n' for rowid in idlist])\n"
 '      \n'
 '\n'
 'def evaluate(prediction,gt):\n'
 '    """\n'
 '    Evaluates the given prediction against the \n'
 '    corresponding ground truth file.\n'
 '    Includes line breaks as characters.\n'
 '\n'
 '    Parameters\n'
 '    ----------\n'
 '    prediction : String\n'
 '        Text transcription to be graded\n'
 '    gt : String\n'
 '        Accepted ground truth transcript\n'
 '\n'
 '    Returns\n'
 '    -------\n'
 '    CER, n_error, n_char\n'
 '\n'
 '    """\n'
 "    n_error = levenshtein(convert(prediction).upper().replace(' ','').replace('\\t',''),gt)\n"
 '    n_char = len(gt)\n'
 '    cer = n_error/n_char\n'
 '    return cer, n_error, n_char\n'
 '\n'
 '\n'
 'def run_evaluations(pred_dir,gt_dir):\n'
 '    """\n'
 '    Runs the evaluation for all files in the ground truth directory.\n'
 '    For a given ground truth file (named SQUEEZE_letters.txt), \n'
 '    it looks for a prediction file named SQUEEZE_pred.txt\n'
 '    containing the transcribed letters.\n'
 '\n'
 '    Parameters\n'
 '    ----------\n'
 '    pred_dir : String, optional\n'
 "        Directory containing prediction files. The default is '.'.\n"
 '    gt_dir : TYPE, optional\n'
 "        Directory containing ground truth files. The default is '.'.\n"
 '\n'
 '    Returns\n'
 '    -------\n'
 '    Mean character error rate.\n'
 '\n'
 '    """\n'
 "    gt_files = [f for f in listdir(gt_dir) if isfile(join(gt_dir, f)) and f[-29:]=='_Rotation1_300dpi_letters.txt']  "
 '# transcript is same for both rotations\n'
 '    cer = []\n'
 '    n_error = []\n'
 '    n_char = []\n'
 '    for gtf in gt_files:\n'
 "        predf = os.path.join(pred_dir,gtf[:-29]+'_transcript.txt')\n"
 '        try:\n'
 '            with open(predf, "r", encoding=\'utf8\') as f:\n'
 '                pred = "".join([line for line in f])\n'
 '        except FileNotFoundError:\n'
 '            if VERBOSE_EVAL:\n'
 '                print(f"Unable to find prediction file \'{predf}\'.")\n'
 '            pred = ""\n'
 '        except Exception as e:\n'
 '            if VERBOSE_EVAL:\n'
 '                print(f"An error occurred: {str(e)} while reading \'{predf}\'.")\n'
 '            pred = ""\n'
 '        pred = convert(pred)\n'
 '        gt = getRowTranscript(os.path.join(gt_dir,gtf))\n'
 '        sq_cer, sq_n_error, sq_n_char = evaluate(pred,gt)\n'
 '        cer.append(sq_cer)\n'
 '        n_error.append(sq_n_error)\n'
 '        n_char.append(sq_n_char)\n'
 '    return sum(n_error)/sum(n_char)\n',
 '# === Line-image extraction from letter-box annotations ===\n'
 '# Mirrors the official getRowTranscript() row ordering, so every cropped line image is\n'
 '# aligned to exactly the ground-truth text that run_evaluations() grades against.\n'
 '# Adds a per-image DESKEW step: we rotate the cleaned image (and the ordered box\n'
 '# corners) by -gangle so every line crop sits horizontally, which is the input\n'
 '# distribution TrOCR was pretrained on.\n'
 'from PIL import Image\n'
 'import math\n'
 '\n'
 '\n'
 'def _ann_for_image(img_path):\n'
 '    return os.path.join(ANN_DIR,\n'
 "                        os.path.basename(img_path).replace('.png', '_letters.txt'))\n"
 '\n'
 '\n'
 'def _row_bbox(row_boxes, W, H, pad=8):\n'
 '    xs = [c for b in row_boxes for c in (b.xnw, b.xne, b.xse, b.xsw)]\n'
 '    ys = [c for b in row_boxes for c in (b.ynw, b.yne, b.yse, b.ysw)]\n'
 '    return (max(0, int(min(xs)) - pad), max(0, int(min(ys)) - pad),\n'
 '            min(W, int(max(xs)) + pad), min(H, int(max(ys)) + pad))\n'
 '\n'
 '\n'
 'def _norm_angle(a):\n'
 '    """Normalize a radian angle to (-pi, pi].\n'
 '\n'
 '    The annotation files sometimes store gangle modulo 2*pi (e.g. 6.149 rad,\n'
 '    which is really -0.134 rad / -7.7 deg) -- we have to unwrap before using it.\n'
 '    """\n'
 '    return (a + math.pi) % (2 * math.pi) - math.pi\n'
 '\n'
 '\n'
 'def _deskew(gray, boxes, gangle, min_deg=0.3):\n'
 '    """Rotate `gray` and the corners of every box so the row baseline is horizontal.\n'
 '\n'
 '    cv2.getRotationMatrix2D uses pixel-space orientation (origin top-left, y axis\n'
 '    pointing down), so a positive angle visually rotates the image clockwise --\n'
 '    which is exactly what we need to undo a positive gangle. Empirically: applying\n'
 '    `+degrees(gangle)` drives the residual top-edge angle of every box to ~0.\n'
 '\n'
 '    gangle is in radians, as returned by readBoxFile(); we normalize to (-pi, pi]\n'
 '    first to handle files that store it modulo 2*pi. We use REPLICATE border so the\n'
 '    deskewed image stays clean around the edges. Box corners are reconstructed with\n'
 '    the original order (NW, SW, SE, NE) preserved so downstream consumers keep working.\n'
 '    """\n'
 '    if gangle is None:\n'
 '        return gray, boxes\n'
 '    gangle = _norm_angle(gangle)\n'
 '    if abs(math.degrees(gangle)) < min_deg:\n'
 '        return gray, boxes\n'
 '    h, w = gray.shape[:2]\n'
 '    angle_deg = math.degrees(gangle)                         # see docstring re: sign\n'
 '    M = cv2.getRotationMatrix2D((w / 2.0, h / 2.0), angle_deg, 1.0)\n'
 "    # Expand canvas so corners aren't clipped.\n"
 '    cos = abs(M[0, 0]); sin = abs(M[0, 1])\n'
 '    new_w = int(h * sin + w * cos)\n'
 '    new_h = int(h * cos + w * sin)\n'
 '    M[0, 2] += (new_w / 2.0) - w / 2.0\n'
 '    M[1, 2] += (new_h / 2.0) - h / 2.0\n'
 '    rotated = cv2.warpAffine(gray, M, (new_w, new_h),\n'
 '                             flags=cv2.INTER_CUBIC,\n'
 '                             borderMode=cv2.BORDER_REPLICATE)\n'
 '    box_cls = type(boxes[0])\n'
 '    out_boxes = []\n'
 '    for b in boxes:\n'
 '        pts = np.array([[b.xnw, b.ynw], [b.xsw, b.ysw],\n'
 '                        [b.xse, b.yse], [b.xne, b.yne]])\n'
 '        pts_h = np.hstack([pts, np.ones((4, 1))])\n'
 '        rot = pts_h @ M.T\n'
 '        out_boxes.append(box_cls(rot[0, 0], rot[0, 1], rot[1, 0], rot[1, 1],\n'
 '                                 rot[2, 0], rot[2, 1], rot[3, 0], rot[3, 1]))\n'
 '    return rotated, out_boxes\n'
 '\n'
 '\n'
 '# --- Line / sub-line extraction ----------------------------------------------\n'
 '# LINE_MAX_CHARS controls letter-box TILING. With None each row is one crop (the\n'
 '# original behaviour). Set LINE_MAX_CHARS (env or here) to split each row into\n'
 '# consecutive chunks of at most that many letters, using the per-letter box\n'
 "# coordinates. Because a chunk's text is just a partition of the row's character\n"
 "# sequence, concatenating a row's chunk transcriptions reproduces the row text exactly\n"
 '# -- no stitching ambiguity -- while each crop keeps far more per-character resolution\n'
 "# than a long row squashed into TrOCR's 384x384 input. Tiling is pipeline-wide: it\n"
 '# affects BOTH training crops (build_pairs) and inference (extract_rows), so the model\n'
 '# is trained and evaluated on the same crop distribution. Tiling is the single biggest\n'
 '# win (test CER 0.21 -> 0.10 in the overnight sweep), so it is ON by default at k=8;\n'
 "# set LINE_MAX_CHARS=0 (or '') to disable and recover the original full-row behaviour.\n"
 "_lmc = os.environ.get('LINE_MAX_CHARS', '8')\n"
 "LINE_MAX_CHARS = int(_lmc) if _lmc not in ('', '0') else None\n"
 '\n'
 '\n'
 'def _balanced_parts(ids, max_chars):\n'
 '    """Split `ids` into nearly-equal contiguous parts of <= max_chars each, avoiding a\n'
 '    tiny trailing chunk that could fall below the min-crop-size guard."""\n'
 '    if not max_chars or max_chars <= 0 or len(ids) <= max_chars:\n'
 '        return [ids]\n'
 '    nck = math.ceil(len(ids) / max_chars)\n'
 '    base, rem, s, parts = len(ids) // nck, len(ids) % nck, 0, []\n'
 '    for c in range(nck):\n'
 '        sz = base + (1 if c < rem else 0)\n'
 '        parts.append(ids[s:s + sz]); s += sz\n'
 '    return parts\n'
 '\n'
 '\n'
 "def extract_rows(img_path, clean=True, deskew=True, max_chars='default'):\n"
 '    """Return [[(PIL \'L\' crop, text), ...chunks...], ...rows...] for one squeeze image.\n'
 '\n'
 "    Uses each image's OWN rotation annotation, so coordinates always match the pixels.\n"
 '    Reading order matches the official getRowTranscript(); rotation/deskew is applied\n'
 '    afterwards to both the image and the ordered boxes. With max_chars set, each row is\n'
 '    tiled into <= max_chars-letter chunks (see LINE_MAX_CHARS)."""\n'
 "    if max_chars == 'default':\n"
 '        max_chars = LINE_MAX_CHARS\n'
 '    ann = _ann_for_image(img_path)\n'
 '    if not os.path.exists(ann):\n'
 '        return []\n'
 '    gangle, boxes, transcript, lines = readBoxFile(ann)\n'
 '    if not boxes or not transcript:\n'
 '        return []\n'
 '    boxes2 = orderBoxes(boxes, gangle, lines)              # transcript reading order\n'
 '    rowlist, idlist = getRowBoxes(boxes2, gangle=gangle)   # ignore multicolumn (as official)\n'
 "    lintran = ''.join(transcript)\n"
 '    gray = to_gray(img_path)\n'
 '    if gray is None:\n'
 '        return []\n'
 '    if clean:\n'
 '        gray = preprocess(gray)\n'
 '    if deskew:\n'
 '        gray, boxes2 = _deskew(gray, boxes2, gangle)\n'
 '    H, W = gray.shape\n'
 '    rows = []\n'
 '    for rowid in idlist:\n'
 '        ids = [i for i in rowid if i < len(lintran)]\n'
 '        if not ids:\n'
 '            continue\n'
 '        chunks = []\n'
 '        for sub in _balanced_parts(ids, max_chars):\n'
 "            text = ''.join(lintran[i] for i in sub).strip()\n"
 '            if not text:\n'
 '                continue\n'
 '            x0, y0, x1, y1 = _row_bbox([boxes2[i] for i in sub], W, H)\n'
 '            if x1 - x0 < 8 or y1 - y0 < 8:\n'
 '                continue\n'
 "            chunks.append((Image.fromarray(gray[y0:y1, x0:x1]).convert('L'), text))\n"
 '        if chunks:\n'
 '            rows.append(chunks)\n'
 '    return rows\n'
 '\n'
 '\n'
 "def extract_lines(img_path, clean=True, deskew=True, max_chars='default'):\n"
 '    """Flat [(PIL \'L\' crop, text), ...] across all rows/chunks (training & simple\n'
 '    consumers). Honours LINE_MAX_CHARS unless max_chars is given explicitly."""\n'
 '    return [c for row in extract_rows(img_path, clean=clean, deskew=deskew,\n'
 '                                      max_chars=max_chars) for c in row]\n'
 '\n'
 '\n'
 '# === Build the line-image dataset for fine-tuning ===\n'
 '# Both rotations contribute lines (each with its OWN aligned annotation) → ~2x data.\n'
 'def build_pairs(df_split):\n'
 '    pairs = []\n'
 '    for _, r in df_split.iterrows():\n'
 "        for col in ('rot1_img', 'rot2_img'):\n"
 '            if r[col]:\n'
 '                pairs.extend(extract_lines(r[col], clean=True))\n'
 '    return pairs\n'
 '\n'
 '\n'
 "train_pairs = build_pairs(index_df[index_df['split'] == 'train'])\n"
 "val_pairs = build_pairs(index_df[index_df['split'] == 'val'])\n"
 'print(f"train lines: {len(train_pairs)}  |  val lines: {len(val_pairs)}")\n'
 '\n'
 '# Peek at a few extracted (line image, text) pairs.\n'
 'fig, axes = plt.subplots(4, 1, figsize=(10, 5))\n'
 'for ax, (im, txt) in zip(axes, train_pairs[:4]):\n'
 "    ax.imshow(im, cmap='gray'); ax.set_axis_off(); ax.set_title(txt, fontsize=8)\n"
 'plt.tight_layout(); plt.show()',
 '# === Synthetic line-crops for low-resource pretraining (legacy optional path) ===\n'
 '# Synthetic data is disabled by default. It was useful as an early regularizer, but it\n'
 '# does not resemble real squeezes closely and varies by installed fonts across machines.\n'
 '# Toggle explicitly with USE_SYNTH=1 / SYNTH_N if you want to run a controlled A/B.\n'
 'import os, random as _r\n'
 'import numpy as np, cv2\n'
 'from PIL import Image, ImageDraw, ImageFont\n'
 'import matplotlib.font_manager as _fm\n'
 '\n'
 "USE_SYNTH = os.environ.get('USE_SYNTH', '0') == '1'\n"
 "SYNTH_N = int(os.environ.get('SYNTH_N', '3000' if USE_SYNTH else '0'))\n"
 "SYNTH_DIR = os.environ.get('SYNTH_DIR', '').strip()\n"
 '\n'
 '# Serif fonts (DejaVu Serif always ships with matplotlib; others used if present).\n'
 "_FONT_CANDS = ['DejaVu Serif', 'Georgia', 'Times New Roman', 'Times', 'PT Serif',\n"
 "               'Liberation Serif', 'Noto Serif']\n"
 'SYNTH_FONTS = []\n'
 'for _name in _FONT_CANDS:\n'
 '    try:\n'
 '        _p = _fm.findfont(_name, fallback_to_default=False)\n'
 '        if _p and os.path.exists(_p) and _p not in SYNTH_FONTS:\n'
 '            SYNTH_FONTS.append(_p)\n'
 '    except Exception:\n'
 '        pass\n'
 'if not SYNTH_FONTS:\n'
 "    SYNTH_FONTS = [_fm.findfont('DejaVu Serif')]\n"
 '\n'
 '# Keep the real train pairs aside so re-running this cell never double-prepends synth.\n'
 "if 'train_pairs_real' not in globals():\n"
 '    train_pairs_real = train_pairs\n'
 '\n'
 '# Character corpus from REAL train rows (uppercased, spaces removed) -> realistic n-grams.\n'
 "_CORPUS = ''.join(ch for _, t in train_pairs_real for ch in t.upper() if not ch.isspace())\n"
 'if len(_CORPUS) < 50:\n'
 "    _CORPUS = 'ABEIKLMNOPRSTUWHYQGDXZ' * 8\n"
 '\n'
 '\n'
 'def _synth_text(rng, lo=8, hi=22):\n'
 '    L = rng.randint(lo, hi)\n'
 '    if len(_CORPUS) > L + 1:\n'
 '        i = rng.randint(0, len(_CORPUS) - L - 1)\n'
 '        return _CORPUS[i:i + L]\n'
 "    return ''.join(rng.choice(_CORPUS) for _ in range(L))\n"
 '\n'
 '\n'
 'def _render_line(text, font_path, rng):\n'
 '    fnt = ImageFont.truetype(font_path, size=rng.randint(48, 72))\n'
 "    l, t, r, b = ImageDraw.Draw(Image.new('L', (8, 8))).textbbox((0, 0), text, font=fnt)\n"
 '    pad = 14\n'
 '    W, H = (r - l) + 2 * pad, (b - t) + 2 * pad\n'
 "    img = Image.new('L', (max(W, 8), max(H, 8)), color=rng.randint(205, 250))  # light bg\n"
 '    ImageDraw.Draw(img).text((pad - l, pad - t), text, font=fnt, fill=rng.randint(20, 90))\n'
 '    return np.asarray(img)\n'
 '\n'
 '\n'
 'def _degrade(arr, rng):\n'
 '    """Turn a crisp rendered line into a RAW raking-light squeeze look: low contrast\n'
 '    (shallow impressions), illumination gradient, soft blur, paper grain and a\n'
 '    low-frequency surface mottle. preprocess() then cleans it exactly like a real scan,\n'
 '    so synthetic and real crops share the same post-processing distribution."""\n'
 '    h, w = arr.shape\n'
 '    a = arr.astype(np.float32)\n'
 '    a = 128 + (a - 128) * rng.uniform(0.30, 0.55)            # shallow -> low contrast\n'
 '    if rng.random() < 0.8:                                   # slight rotation\n'
 '        M = cv2.getRotationMatrix2D((w / 2, h / 2), rng.uniform(-2.5, 2.5), 1.0)\n'
 '        a = cv2.warpAffine(a, M, (w, h), flags=cv2.INTER_LINEAR,\n'
 '                           borderMode=cv2.BORDER_REPLICATE)\n'
 '    if rng.random() < 0.5:                                   # stroke weight\n'
 '        k = np.ones((2, 2), np.uint8)\n'
 '        a = (cv2.erode if rng.random() < 0.5 else cv2.dilate)(a, k, iterations=1)\n'
 '    a = cv2.GaussianBlur(a, (0, 0), sigmaX=rng.uniform(0.8, 2.0))   # shallow blur\n'
 '    yy, xx = np.mgrid[0:h, 0:w].astype(np.float32)          # raking-light gradient\n'
 '    g = (1.0 + rng.uniform(-0.35, 0.35) * (xx / max(w, 1) - 0.5)\n'
 '             + rng.uniform(-0.35, 0.35) * (yy / max(h, 1) - 0.5))\n'
 '    a = a * g\n'
 '    cs = max(2, int(min(h, w) / rng.uniform(3, 6)))         # low-frequency surface mottle\n'
 '    coarse = np.random.normal(0, rng.uniform(6, 16), (cs, cs)).astype(np.float32)\n'
 '    a = a + cv2.resize(coarse, (w, h), interpolation=cv2.INTER_CUBIC)\n'
 '    a = a + np.random.normal(0, rng.uniform(4, 10), (h, w))  # fine paper grain\n'
 '    return preprocess(np.clip(a, 0, 255).astype(np.uint8))   # SAME cleaning as real scans\n'
 '\n'
 '\n'
 'def make_synthetic_pairs(n, seed=123):\n'
 '    rng = _r.Random(seed)\n'
 '    out = []\n'
 '    for _ in range(n):\n'
 '        txt = _synth_text(rng)\n'
 '        arr = _degrade(_render_line(txt, rng.choice(SYNTH_FONTS), rng), rng)\n'
 "        out.append((Image.fromarray(arr, mode='L'), txt))\n"
 '    return out\n'
 '\n'
 '\n'
 'if USE_SYNTH and SYNTH_DIR:\n'
 '    import sys as _sys\n'
 "    _sys.path.insert(0, os.path.abspath('scripts'))\n"
 '    import synth_physics as _synth_physics\n'
 '    synth_pairs = _synth_physics.load_pairs(SYNTH_DIR, limit=SYNTH_N or None)\n'
 '    train_pairs = synth_pairs + train_pairs_real        # real lines still present\n'
 '    print(f"Physics synthetic pairs: {len(synth_pairs)} from {SYNTH_DIR} -> "\n'
 '          f"train lines now {len(train_pairs)} (real={len(train_pairs_real)})")\n'
 'elif USE_SYNTH:\n'
 '    synth_pairs = make_synthetic_pairs(SYNTH_N)\n'
 '    train_pairs = synth_pairs + train_pairs_real        # real lines still present\n'
 '    print(f"Legacy font synthetic pairs: {len(synth_pairs)} (fonts={len(SYNTH_FONTS)}) -> "\n'
 '          f"train lines now {len(train_pairs)} (real={len(train_pairs_real)})")\n'
 '    import matplotlib.pyplot as plt\n'
 '    fig, axes = plt.subplots(4, 1, figsize=(10, 5))\n'
 '    for ax, (im, txt) in zip(axes, synth_pairs[:4]):\n'
 "        ax.imshow(im, cmap='gray'); ax.set_axis_off(); ax.set_title(txt, fontsize=8)\n"
 '    plt.tight_layout(); plt.show()\n'
 'else:\n'
 '    train_pairs = train_pairs_real\n'
 '    print("USE_SYNTH=0 -> training on real line-crops only.")\n',
 '# === Fine-tune TrOCR on squeeze line-crops (Phase 2 recipe) ===\n'
 '# Improvements over the original: synthetic-data augmentation (previous cell),\n'
 '# aspect-ratio-preserving input (prep_image), label smoothing + cosine LR schedule\n'
 '# + warmup, stronger geometric augmentation, configurable base ckpt / epoch count.\n'
 'import random as _rand\n'
 'from torch.utils.data import Dataset\n'
 'from transformers import (Seq2SeqTrainer, Seq2SeqTrainingArguments,\n'
 '                          default_data_collator)\n'
 'from transformers.utils import logging as hf_logging\n'
 'hf_logging.set_verbosity_error()\n'
 'from textdistance import levenshtein\n'
 '\n'
 'MAX_LEN = 64\n'
 '_AUG_RNG = _rand.Random(42)\n'
 '\n'
 '\n'
 'def _augment(im):\n'
 '    """Light, label-preserving augmentation for ONE PIL \'L\' (grayscale) line image.\n'
 '\n'
 '    Each transform fires independently with low-ish probability; effects compose.\n'
 '    Designed to mimic the residual noise/skew we actually see on squeezes:\n'
 '      brightness +/- 10%, contrast +/- 10%, +/- 1.5 deg residual rotation,\n'
 '      single-pixel erosion or dilation, light gaussian speckle (sigma=2.5).\n'
 '    """\n'
 '    arr = np.array(im, dtype=np.uint8)\n'
 '    # brightness\n'
 '    if _AUG_RNG.random() < 0.5:\n'
 '        arr = np.clip(arr.astype(np.int16) +\n'
 '                      _AUG_RNG.randint(-25, 25), 0, 255).astype(np.uint8)\n'
 '    # contrast\n'
 '    if _AUG_RNG.random() < 0.5:\n'
 '        f = 1.0 + _AUG_RNG.uniform(-0.10, 0.10)\n'
 '        arr = np.clip((arr.astype(np.float32) - 128) * f + 128, 0, 255).astype(np.uint8)\n'
 '    # tiny residual rotation (deskew was already applied upstream)\n'
 '    if _AUG_RNG.random() < 0.4:\n'
 '        h, w = arr.shape\n'
 '        ang = _AUG_RNG.uniform(-1.5, 1.5)\n'
 '        M = cv2.getRotationMatrix2D((w / 2, h / 2), ang, 1.0)\n'
 '        arr = cv2.warpAffine(arr, M, (w, h),\n'
 '                             flags=cv2.INTER_CUBIC,\n'
 '                             borderMode=cv2.BORDER_REPLICATE)\n'
 '    # small horizontal shear (heavier geometric augmentation)\n'
 '    if _AUG_RNG.random() < 0.25:\n'
 '        h, w = arr.shape\n'
 '        M = np.float32([[1, _AUG_RNG.uniform(-0.12, 0.12), 0], [0, 1, 0]])\n'
 '        arr = cv2.warpAffine(arr, M, (w, h), flags=cv2.INTER_LINEAR,\n'
 '                             borderMode=cv2.BORDER_REPLICATE)\n'
 '    # morphology -- simulates over- vs under-exposed squeezes\n'
 '    if _AUG_RNG.random() < 0.3:\n'
 '        k = np.ones((2, 2), np.uint8)\n'
 '        arr = (cv2.erode if _AUG_RNG.random() < 0.5 else cv2.dilate)(arr, k, iterations=1)\n'
 "    # very mild speckle so the model doesn't memorize background grain\n"
 '    if _AUG_RNG.random() < 0.3:\n'
 '        noise = np.random.normal(0, 2.5, arr.shape).astype(np.int16)\n'
 '        arr = np.clip(arr.astype(np.int16) + noise, 0, 255).astype(np.uint8)\n'
 '    # --- Degradation-aware augmentation, opt-in via AUG_LEVEL (0=off=original behavior) -----\n'
 '    # Targets the failure physics seen in the error gallery (worn/merged strokes behind Lambda/Alpha\n'
 '    # crossbars & Theta bars, raking-light shading, chips, resolution loss). TRAIN-only.\n'
 '    import os as _os\n'
 "    _lvl = int(_os.environ.get('AUG_LEVEL', '0'))\n"
 '    if _lvl > 0:\n'
 '        _p = 0.30 if _lvl == 1 else 0.45\n'
 '        h, w = arr.shape\n'
 '        # (1) stroke-width jitter: stronger/variable erode|dilate (worn vs over-pressed strokes)\n'
 '        if _AUG_RNG.random() < _p:\n'
 '            ks = _AUG_RNG.choice([2, 3] if _lvl == 1 else [2, 3, 3])\n'
 '            k2 = np.ones((ks, ks), np.uint8)\n'
 '            arr = (cv2.erode if _AUG_RNG.random() < 0.5 else cv2.dilate)(\n'
 '                arr, k2, iterations=_AUG_RNG.randint(1, 2))\n'
 '        # (2) elastic / local warp: non-rigid paper-cast stretch (classic HTR aug, was missing)\n'
 '        if _AUG_RNG.random() < _p:\n'
 '            alpha = 4.0 if _lvl == 1 else 7.0\n'
 '            dx = cv2.GaussianBlur((np.random.rand(h, w) * 2 - 1).astype(np.float32), (0, 0), 6.0)\n'
 '            dy = cv2.GaussianBlur((np.random.rand(h, w) * 2 - 1).astype(np.float32), (0, 0), 6.0)\n'
 '            xx, yy = np.meshgrid(np.arange(w), np.arange(h))\n'
 '            arr = cv2.remap(arr, (xx + alpha * dx).astype(np.float32),\n'
 '                            (yy + alpha * dy).astype(np.float32),\n'
 '                            interpolation=cv2.INTER_LINEAR, borderMode=cv2.BORDER_REPLICATE)\n'
 '        # (3) raking-light shading: random directional brightness gradient\n'
 '        if _AUG_RNG.random() < _p:\n'
 '            amp = 0.25 if _lvl == 1 else 0.40\n'
 '            ang = _AUG_RNG.uniform(0, 6.2831853)\n'
 '            gx, gy = np.meshgrid(np.linspace(-1, 1, w), np.linspace(-1, 1, h))\n'
 '            grad = np.cos(ang) * gx + np.sin(ang) * gy\n'
 '            grad = grad / (np.abs(grad).max() + 1e-6)\n'
 '            arr = np.clip(arr.astype(np.float32) * (1.0 + amp * grad), 0, 255).astype(np.uint8)\n'
 '        # (4) cutout: chips / missing relief (fill with median tone)\n'
 '        if _AUG_RNG.random() < _p:\n'
 '            med = int(np.median(arr))\n'
 '            for _ in range(_AUG_RNG.randint(1, 2 if _lvl == 1 else 3)):\n'
 '                cw = _AUG_RNG.randint(max(2, w // 12), max(3, w // 6))\n'
 '                ch = _AUG_RNG.randint(max(2, h // 6), max(3, h // 3))\n'
 '                x0 = _AUG_RNG.randint(0, max(1, w - cw)); y0 = _AUG_RNG.randint(0, max(1, h - ch))\n'
 '                arr[y0:y0 + ch, x0:x0 + cw] = med\n'
 '        # (5) resolution jitter: focus/scan blur via down- then up-sample\n'
 '        if _AUG_RNG.random() < _p:\n'
 '            f = _AUG_RNG.uniform(0.5 if _lvl == 2 else 0.65, 0.9)\n'
 '            small = cv2.resize(arr, (max(1, int(w * f)), max(1, int(h * f))), interpolation=cv2.INTER_AREA)\n'
 '            arr = cv2.resize(small, (w, h), interpolation=cv2.INTER_LINEAR)\n'
 "    return Image.fromarray(arr, mode='L')\n"
 '\n'
 '\n'
 'class LineDataset(Dataset):\n'
 '    def __init__(self, pairs, training=False):\n'
 '        self.pairs = [(im, t) for im, t in pairs if 0 < len(t) <= MAX_LEN]\n'
 '        self.training = training\n'
 '\n'
 '    def __len__(self):\n'
 '        return len(self.pairs)\n'
 '\n'
 '    def __getitem__(self, i):\n'
 '        im, text = self.pairs[i]\n'
 '        if self.training:\n'
 '            im = _augment(im)\n'
 "        pix = processor(images=prep_image(im), return_tensors='pt').pixel_values[0]\n"
 "        ids = processor.tokenizer(text, padding='max_length', truncation=True,\n"
 '                                  max_length=MAX_LEN).input_ids\n'
 '        ids = [t if t != processor.tokenizer.pad_token_id else -100 for t in ids]\n'
 "        return {'pixel_values': pix, 'labels': torch.tensor(ids)}\n"
 '\n'
 '\n'
 'def compute_metrics(pred):\n'
 '    preds = pred.predictions[0] if isinstance(pred.predictions, tuple) else pred.predictions\n'
 '    preds = np.asarray(preds)\n'
 '    if preds.ndim != 2:\n'
 "        raise ValueError(f'Expected generated token ids, got predictions with shape {preds.shape}')\n"
 '    if np.any((preds < 0) | (preds >= len(processor.tokenizer))):\n'
 "        raise ValueError('Generated predictions contain token ids outside the tokenizer vocabulary')\n"
 '    label_ids = pred.label_ids.copy()\n'
 '    label_ids[label_ids == -100] = processor.tokenizer.pad_token_id\n'
 '    pred_str = processor.batch_decode(preds.astype(np.int64), skip_special_tokens=True)\n'
 '    label_str = processor.batch_decode(label_ids, skip_special_tokens=True)\n'
 '    n_err = sum(levenshtein(p.upper(), l.upper()) for p, l in zip(pred_str, label_str))\n'
 '    n_chr = sum(len(l) for l in label_str) or 1\n'
 "    return {'cer': n_err / n_chr}\n"
 '\n'
 '\n'
 '# ---- Resume-from-checkpoint cache --------------------------------------------\n'
 '# Re-running this cell from a fresh kernel should NOT retrain from scratch if a\n'
 '# good checkpoint already exists on disk. Set TROCR_FORCE_TRAIN=1 to force a\n'
 '# fresh training run (e.g. after changing hyper-parameters or the dataset).\n'
 'import glob, json as _json\n'
 "CKPT_DIR = os.path.join(WORK_DIR, 'trocr_ft')\n"
 "FORCE_TRAIN = os.environ.get('TROCR_FORCE_TRAIN', '0') == '1'\n"
 '\n'
 'def _configure_generation(model):\n'
 '    """Keep generation explicit for trainer eval; direct inference still passes max_new_tokens."""\n'
 '    model.config.max_length = None\n'
 '    model.config.num_beams = None\n'
 '    model.generation_config.max_length = MAX_LEN\n'
 '    model.generation_config.num_beams = 1\n'
 '    model.generation_config.max_new_tokens = None\n'
 '    return model\n'
 '\n'
 'def _pick_best_ckpt(d):\n'
 '    """Return (path, eval_cer) for the lowest-eval-CER checkpoint in `d`, or (None, None)."""\n'
 '    best = None\n'
 "    for ck in sorted(glob.glob(os.path.join(d, 'checkpoint-*')),\n"
 "                     key=lambda p: int(p.rsplit('-', 1)[-1])):\n"
 "        ts = os.path.join(ck, 'trainer_state.json')\n"
 '        if not os.path.exists(ts):\n'
 '            continue\n'
 '        st = _json.load(open(ts))\n'
 '        # Prefer the checkpoint that HF itself marked best (load_best_model_at_end=True);\n'
 '        # otherwise fall back to the newest one.\n'
 "        bp = st.get('best_model_checkpoint')\n"
 '        if bp and os.path.isdir(bp):\n'
 "            cer = st.get('best_metric')\n"
 '            return bp, cer\n'
 "        last_ev = [e for e in st.get('log_history', []) if e.get('eval_cer') is not None]\n"
 '        if last_ev:\n'
 "            best = (ck, last_ev[-1]['eval_cer'])\n"
 '    return best if best else (None, None)\n'
 '\n'
 '\n'
 'resume_path, resume_cer = _pick_best_ckpt(CKPT_DIR)\n'
 'if resume_path and not FORCE_TRAIN:\n'
 '    print(f"Loading cached fine-tuned model from {resume_path}"\n'
 '          + (f"  (val CER={resume_cer:.4f})" if resume_cer is not None else ""))\n'
 '    ft_model = _configure_generation(VisionEncoderDecoderModel.from_pretrained(resume_path, '
 'low_cpu_mem_usage=False).to(device)).eval()\n'
 '    trainer = None\n'
 'else:\n'
 '    if FORCE_TRAIN and resume_path:\n'
 '        print(f"TROCR_FORCE_TRAIN=1 -> ignoring existing checkpoint at {resume_path}")\n'
 '    ft_model = _configure_generation(VisionEncoderDecoderModel.from_pretrained(BASE_CKPT, '
 'low_cpu_mem_usage=False).to(device))\n'
 '    ft_model.config.decoder_start_token_id = processor.tokenizer.cls_token_id\n'
 '    ft_model.config.pad_token_id = processor.tokenizer.pad_token_id\n'
 '    ft_model.config.eos_token_id = processor.tokenizer.sep_token_id\n'
 '    ft_model.config.vocab_size = ft_model.config.decoder.vocab_size\n'
 '    ft_model.generation_config.decoder_start_token_id = processor.tokenizer.cls_token_id\n'
 '    ft_model.generation_config.pad_token_id = processor.tokenizer.pad_token_id\n'
 '    ft_model.generation_config.eos_token_id = processor.tokenizer.sep_token_id\n'
 '\n'
 "    NUM_EPOCHS = int(os.environ.get('TROCR_EPOCHS', '8'))\n"
 '    args = Seq2SeqTrainingArguments(\n'
 '        output_dir=CKPT_DIR, predict_with_generate=True,\n'
 '        generation_max_length=MAX_LEN, generation_num_beams=1,\n'
 '        per_device_train_batch_size=8, per_device_eval_batch_size=8,\n'
 '        num_train_epochs=NUM_EPOCHS, learning_rate=5e-5, fp16=USE_FP16,\n'
 "        lr_scheduler_type='cosine', warmup_ratio=0.1,\n"
 '        dataloader_pin_memory=False,\n'
 "        eval_strategy='epoch', save_strategy='epoch', save_total_limit=1,\n"
 "        load_best_model_at_end=True, metric_for_best_model='cer',\n"
 "        greater_is_better=False, logging_steps=50, report_to='none')\n"
 '\n'
 '    trainer = Seq2SeqTrainer(\n'
 '        model=ft_model, args=args,\n'
 '        train_dataset=LineDataset(train_pairs, training=True),\n'
 '        eval_dataset=LineDataset(val_pairs, training=False),\n'
 '        data_collator=default_data_collator, compute_metrics=compute_metrics)\n'
 '    trainer.train()\n'
 '    ft_model.eval()\n'
 '    print("Fine-tuning complete.")\n',
 '# === Character n-gram LM for shallow-fusion rescoring (Phase 3, item 9) ===\n'
 '# Inscriptions are formulaic, so a small char-level LM over the corpus transcripts can\n'
 '# fix single-character and line-length slips. We train an interpolated (Jelinek-Mercer)\n'
 "# char n-gram on the TRAIN+VAL row transcripts (no test leakage), then rescore TrOCR's\n"
 '# top-N beams by  mean_logp_TrOCR + w * mean_logp_LM  (w tuned on val in the next cell).\n'
 '# trocr_decode() generalizes the decode helpers to optionally perform this rerank.\n'
 'import math\n'
 'from collections import Counter, defaultdict\n'
 '\n'
 '\n'
 'class CharNGramLM:\n'
 '    def __init__(self, order=6, lam=0.4):\n'
 '        self.order, self.lam = order, lam\n'
 '        self.counts = [defaultdict(Counter) for _ in range(order + 1)]   # counts[m]: ctx(len m-1)->next char\n'
 '        self.vocab = set()\n'
 '\n'
 '    def train(self, lines):\n'
 '        for ln in lines:\n'
 '            if not ln:\n'
 '                continue\n'
 '            self.vocab.update(ln)\n'
 '            for i, ch in enumerate(ln):\n'
 '                for m in range(1, self.order + 1):\n'
 '                    ctx = ln[i - (m - 1):i]\n'
 '                    if len(ctx) == m - 1:\n'
 '                        self.counts[m][ctx][ch] += 1\n'
 '        return self\n'
 '\n'
 '    def cond_logprob(self, ch, context):\n'
 '        p = 1.0 / max(len(self.vocab), 1)                # order-0 uniform base\n'
 '        for m in range(1, self.order + 1):\n'
 "            ctx = context[-(m - 1):] if m > 1 else ''\n"
 '            cnt = self.counts[m].get(ctx)\n'
 '            ph = (cnt.get(ch, 0) / sum(cnt.values())) if cnt else 0.0\n'
 '            p = self.lam * ph + (1 - self.lam) * p\n'
 '        return math.log(max(p, 1e-12))\n'
 '\n'
 '    def mean_logprob(self, text):\n'
 '        if not text:\n'
 '            return 0.0\n'
 '        return sum(self.cond_logprob(text[i], text[:i]) for i in range(len(text))) / len(text)\n'
 '\n'
 '\n'
 '# Train on TRAIN+VAL row transcripts (split rows on newlines; uppercase; drop blanks).\n'
 '_lm_lines = []\n'
 "for _, r in index_df[index_df['split'].isin(['train', 'val'])].iterrows():\n"
 "    _lm_lines += [ln for ln in getRowTranscript(r['ann_path']).upper().split('\\n') if ln]\n"
 'char_lm = CharNGramLM(order=6, lam=0.4).train(_lm_lines)\n'
 ''
 '\n'
 '\n'
 '@torch.no_grad()\n'
 'def trocr_decode(model, pil_lines, bs=16, max_new_tokens=64, num_beams=1,\n'
 '                 logits_processor=None, lm=None, lm_weight=0.0, n_best=1):\n'
 '    """Return (texts, scores). With lm set, rerank the top-n_best beams per crop by\n'
 "    mean_logp_TrOCR + lm_weight * lm.mean_logprob(text). The chosen candidate's fused\n"
 '    score is returned too, reused as the confidence for the dual-rotation ensemble."""\n'
 '    nrs = n_best if lm is not None else 1\n'
 '    nb = max(num_beams, nrs)\n'
 '    texts, scores = [], []\n'
 '    for i in range(0, len(pil_lines), bs):\n'
 '        batch = [prep_image(im) for im in pil_lines[i:i + bs]]\n'
 "        pix = processor(images=batch, return_tensors='pt').pixel_values.to(device)\n"
 '        gen = model.generate(pix, max_new_tokens=max_new_tokens, use_cache=True,\n'
 '                             num_beams=nb, num_return_sequences=nrs,\n'
 '                             logits_processor=logits_processor,\n'
 '                             output_scores=True, return_dict_in_generate=True)\n'
 '        tr = model.compute_transition_scores(\n'
 "            gen.sequences, gen.scores, getattr(gen, 'beam_indices', None),\n"
 '            normalize_logits=True)\n'
 '        finite = torch.isfinite(tr)\n'
 '        conf = (tr.masked_fill(~finite, 0.0).sum(1) / finite.sum(1).clamp(min=1)).float().cpu().tolist()\n'
 '        dec = processor.batch_decode(gen.sequences, skip_special_tokens=True)\n'
 '        for b in range(len(batch)):\n'
 '            best_t, best_s = None, None\n'
 '            for j in range(b * nrs, b * nrs + nrs):\n'
 '                s = conf[j] + (lm_weight * lm.mean_logprob(dec[j].upper()) if lm is not None else 0.0)\n'
 '                if best_s is None or s > best_s:\n'
 '                    best_s, best_t = s, dec[j]\n'
 '            texts.append(best_t); scores.append(best_s)\n'
 '    return texts, scores\n'
 '\n'
 '\n'
 '# Val ground-truth dir (for tuning the LM weight in the next cell).\n'
 "VAL_GT_DIR = os.path.join(WORK_DIR, 'gt_val')\n"
 'shutil.rmtree(VAL_GT_DIR, ignore_errors=True); os.makedirs(VAL_GT_DIR)\n'
 "for _, r in index_df[index_df['split'] == 'val'].iterrows():\n"
 "    shutil.copy(r['ann_path'], VAL_GT_DIR)\n",
 '# === Fine-tuned TrOCR CER on the (official) test split ===\n'
 '# Decoding ablation -- each row adds one upgrade so its contribution is visible:\n'
 '#   greedy/Rot1 -> beam -> +alphabet constraint -> +char-LM rescoring -> +dual-rotation\n'
 '#   ensemble. The char-LM fusion weight is tuned on the VAL split (no test leakage).\n'
 'import pandas as pd\n'
 '\n'
 'ALPHABET = sorted({c for _, t in (train_pairs + val_pairs) for c in t.upper()\n'
 '                   if not c.isspace()})\n'
 "print('Learned alphabet:', ''.join(ALPHABET))\n"
 "LP_CHARSET = make_logits_processor(ALPHABET, mode='charset')\n"
 'NUM_BEAMS = 5\n'
 'N_BEST = 5                        # beams rescored by the char LM\n'
 '\n'
 '\n'
 'def _decode_rows(model, img_path, num_beams, logits_processor, lm=None, lm_weight=0.0):\n'
 '    """Decode one image into rows of (text, conf) chunk-tuples (tiling- & LM-aware)."""\n'
 '    rows = extract_rows(img_path, clean=True)\n'
 '    flat = [im for row in rows for im, _ in row]\n'
 '    if not flat:\n'
 '        return []\n'
 '    texts, confs = trocr_decode(model, flat, num_beams=num_beams,\n'
 '                                logits_processor=logits_processor, lm=lm,\n'
 '                                lm_weight=lm_weight, n_best=(N_BEST if lm is not None else 1))\n'
 '    out, k = [], 0\n'
 '    for row in rows:\n'
 '        out.append(list(zip(texts[k:k + len(row)], confs[k:k + len(row)]))); k += len(row)\n'
 '    return out\n'
 '\n'
 '\n'
 'def transcribe_squeeze_cfg(model, rec, num_beams=1, logits_processor=None,\n'
 '                           ensemble=False, lm=None, lm_weight=0.0):\n'
 '    """Transcribe one squeeze; tiling/LM-aware. If ensemble, keep the more confident\n'
 '    reading per chunk across the two rotations (whole-row fallback on chunk-count\n'
 '    disagreement)."""\n'
 '    dk = dict(num_beams=num_beams, logits_processor=logits_processor,\n'
 '              lm=lm, lm_weight=lm_weight)\n'
 '    if not ensemble:\n'
 "        rows = _decode_rows(model, rec['rot1_img'], **dk)\n"
 "        return '\\n'.join(''.join(t for t, _ in row) for row in rows)\n"
 "    views = [_decode_rows(model, rec[c], **dk) for c in ('rot1_img', 'rot2_img') if rec[c]]\n"
 '    views = [v for v in views if v]\n'
 '    if not views:\n'
 "        return ''\n"
 '    out_rows = []\n'
 '    for ri in range(max(len(v) for v in views)):\n'
 '        variants = [v[ri] for v in views if ri < len(v)]\n'
 '        if len({len(rv) for rv in variants}) == 1:                # same chunk count -> per-chunk\n'
 '            row = [max((rv[ci] for rv in variants), key=lambda c: c[1])[0]\n'
 '                   for ci in range(len(variants[0]))]\n'
 "            out_rows.append(''.join(row))\n"
 '        else:                                                     # disagree -> whole-row by mean conf\n'
 '            best = max(variants, key=lambda rv: sum(c for _, c in rv) / max(len(rv), 1))\n'
 "            out_rows.append(''.join(t for t, _ in best))\n"
 "    return '\\n'.join(out_rows)\n"
 '\n'
 '\n'
 'def eval_on(model, df, gt_dir, subdir, **kw):\n'
 '    d = os.path.join(WORK_DIR, subdir)\n'
 '    shutil.rmtree(d, ignore_errors=True); os.makedirs(d)\n'
 '    for _, r in df.iterrows():\n'
 '        with open(os.path.join(d, f"{r[\'base\']}_transcript.txt"), \'w\', encoding=\'utf8\') as f:\n'
 '            _txt = transcribe_squeeze_cfg(model, r, **kw)\n'
 "            f.write(_txt if _txt.endswith('\\n') else _txt + '\\n')  # GT ends every row (incl. last) with a "
 'newline\n'
 '    return run_evaluations(d, gt_dir)\n'
 '\n'
 '\n'
 '# Tune the char-LM fusion weight on VAL (no test leakage).\n'
 "val_df = index_df[index_df['split'] == 'val']\n"
 "print('Tuning char-LM weight on val:')\n"
 'lm_sweep = {}\n'
 'for w in [0.0, 0.15, 0.3, 0.5]:\n'
 "    vcer = eval_on(ft_model, val_df, VAL_GT_DIR, 'pred_val', num_beams=NUM_BEAMS,\n"
 '                   logits_processor=LP_CHARSET,\n'
 '                   lm=(char_lm if w > 0 else None), lm_weight=w)\n'
 '    lm_sweep[w] = vcer\n'
 '    print(f"  w={w:<4} val CER = {vcer:.4f}")\n'
 'LM_WEIGHT = min(lm_sweep, key=lm_sweep.get)\n'
 'print(f"Chosen LM weight (by val CER): {LM_WEIGHT}")\n'
 '\n'
 '_lm = (char_lm if LM_WEIGHT > 0 else None)\n'
 'configs = [\n'
 "    ('greedy / Rotation1 (original)',      dict(num_beams=1)),\n"
 "    (f'beam ({NUM_BEAMS})',                 dict(num_beams=NUM_BEAMS)),\n"
 "    ('beam + alphabet constraint',         dict(num_beams=NUM_BEAMS, logits_processor=LP_CHARSET)),\n"
 "    (f'+ char-LM rescore (w={LM_WEIGHT})',  dict(num_beams=NUM_BEAMS, logits_processor=LP_CHARSET, lm=_lm, "
 'lm_weight=LM_WEIGHT)),\n'
 "    ('+ dual-rotation ensemble',           dict(num_beams=NUM_BEAMS, logits_processor=LP_CHARSET, lm=_lm, "
 'lm_weight=LM_WEIGHT, ensemble=True)),\n'
 ']\n'
 'print("Fine-tuned TrOCR -- decoding ablation (official test CER):")\n'
 'results = []\n'
 'for name, kw in configs:\n'
 "    cer = eval_on(ft_model, test_df, GT_DIR, 'pred_ft', **kw)\n"
 '    print(f"  {name:<40} CER = {cer:.4f}")\n'
 '    results.append((name, cer, kw))\n'
 '\n'
 "ablation = pd.DataFrame([(n, c) for n, c, _ in results], columns=['decoding', 'CER'])\n"
 "display(ablation.style.format({'CER': '{:.4f}'}).hide(axis='index'))\n"
 '\n'
 'best_name, ft_cer, best_kw = min(results, key=lambda x: x[1])\n'
 'ft_cer = float(ft_cer)\n'
 "# Persist the BEST configuration's predictions for the downstream per-cluster cell.\n"
 "PRED_FT = os.path.join(WORK_DIR, 'pred_ft')\n"
 "eval_on(ft_model, test_df, GT_DIR, 'pred_ft', **best_kw)\n"
 'print(f"\\nBest decoding: {best_name}")\n'
 'print(f"BASELINE  CER : {baseline_cer:.4f}")\n'
 'print(f"FINE-TUNED CER (best decoding): {ft_cer:.4f}")\n'
 'if baseline_cer > 0:\n'
 '    print(f"Improvement   : {baseline_cer - ft_cer:.4f} absolute "\n'
 '          f"({100 * (baseline_cer - ft_cer) / baseline_cer:.1f}% relative)")\n'
 '\n'
 '# Quick qualitative peek -- 5 lines from a single test squeeze, baseline vs fine-tuned.\n'
 "demo = extract_lines(test_df.iloc[0]['rot1_img'], clean=True)[:5]\n"
 'preds_b = trocr_transcribe(baseline_model, [im for im, _ in demo])\n'
 'preds_f = trocr_transcribe(ft_model, [im for im, _ in demo],\n'
 '                           num_beams=NUM_BEAMS, logits_processor=LP_CHARSET)\n'
 'print("\\nExample line predictions (test squeeze 0):")\n'
 'for (im, gt), pb, pf in zip(demo, preds_b, preds_f):\n'
 '    print(f"  GT       : {gt}")\n'
 '    print(f"  BASELINE : {pb.upper()}")\n'
 '    print(f"  FINE-TUNE: {pf.upper()}\\n")\n']
